<?php

/**
 * Implements hook_menu().
 * Approve level settings/PR roles involved
 */
function camplus_pr_menu() {
	$items = array();
  $items['admin/config/camplus'] = array(
    'title' => 'Education Groupware',
    'position' => 'left',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('camplus bi settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/camplus/pr_settings'] = array(
    'title' => t('PR settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_settings_form'),
    'access arguments' => array('camplus bi settings'),
    'file' => 'camplus_pr.pages.inc',
  );
  $items['admin/config/camplus/pr_settings/rang_count'] = array(
    'title' => t('Basic Setting'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_settings_form'),
    'access arguments' => array('camplus bi settings'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' =>-28,
  );

  //PR range settings
  $items['admin/config/camplus/pr_settings/range_settings'] = array(
    'title' => t('PR range settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_range_settings_form'),
    'access arguments' => array('camplus bi settings'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-27,
  );
	$items['admin/config/camplus/pr_settings/roles_involved'] = array(
		'title' => t('PR roles involved'),
		'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_roles_involved_settings_form'),
    'access arguments' => array('camplus bi settings'),
		'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-26,
	);
  $items['admin/config/camplus/pr_settings/roles_weight'] = array(
    'title' => t('PR roles weight'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_roles_weight_settings_form'),
    'access arguments' => array('camplus bi settings'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-25,
  );
  $items['admin/config/camplus/pr_settings/pr_approve_settings'] = array(
    'title' => t('Approval Workflow'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_approve_settings_form'),
    'access arguments' => array('camplus bi settings'),
    'file' => 'camplus_pr.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' =>-24,
  );
  // $items['admin/config/camplus/advanced_management/budget/settings'] = array(
  //   'title' => 'Budget settings',
  //   'page callback' => 'drupal_get_form',
  //   'page arguments' => array('camplus_pr_budget_settings_form'),
  //   'access arguments' => array('camplus budget settings'),
  //   'file' => 'camplus_pr.pages.inc',
  //   'weight' => 7,
  //   'type' => MENU_LOCAL_TASK,
  // );

  // $items['pr'] = array(
  //   'title' => 'My Budget Report',
  //   'access arguments' => array('view budget report'),
  //   'weight' => 5,
  //   'menu_name' => 'main-menu',
  //   'page callback' => 'drupal_get_form',
  //   'page arguments' => array('camplus_pr_budget_settings_form'), 
  //   'access arguments' => array('view my budget report'), 
  //   'file' => 'camplus_pr.pages.inc',
  // );

  $items['pr/my_budget_report'] = array(
    'title' => 'My Budget Report',
    'access arguments' => array('view budget report'),
    'weight' => 5,
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_budget_settings_form'), 
    'access arguments' => array('create purchase_request content'), 
    'file' => 'camplus_pr.pages.inc',
  );
  $items['pr/budget_report'] = array(
    'title' => 'Budget Report',
    'access arguments' => array('view budget report'),
    'weight' => 5,
    'type' => MENU_LOCAL_TASK, 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camplus_pr_budget_settings_form'), 
    'file' => 'camplus_pr.pages.inc',
  );
  $items['node/%node/undraft'] =  array(
    'title' => 'undraft pr',
    'page callback' => 'camplus_pr_undraft',
    'page arguments' => array(1),
    'access arguments' => array('create purchase_request content'),
    'type' => MENU_CALLBACK,
  );
	return $items;
}

function camplus_pr_undraft($node) {
  //如果预算还有，才可以通过
  $field_budget_items_amount = 0;
  foreach ($node->field_budget_items_amount[LANGUAGE_NONE] as $key => $value) {
    $field_budget_items_amount +=  $value['value'];
  }
  $total = $field_budget_items_amount + $node->field_payment_from_students[LANGUAGE_NONE][0]['value'];
  $budget_nid = $node->field_budget_items[LANGUAGE_NONE][0]['target_id'];
  $bis_info_all = get_bis_info_all($budget_nid);
  if( $total > $bis_info_all['g']) {
    drupal_set_message(t('Sorry, your requested amount currently exceeds the Maximum Budget in your Department, your application CANNOT be submitted!'), 'warning', FALSE);
    drupal_goto('node/'.$node->nid);
    //return
  }
  //variable_get('camplus_pr_enable_mixable_key', 1), 不可通用时
  if(!variable_get('camplus_pr_enable_mixable_key') ) {
    if($total > $bis_info_all['f']) {
        drupal_set_message(t('Sorry, your requested amount currently exceeds the Maximum Budget in your Department, your application CANNOT be submitted!'), 'warning', FALSE);
        //Sorry, not enable mixable key,cannot submit!
        drupal_goto('node/'.$node->nid);
    }
  }
  $node->status = 1;
  $node->changed = time();
  // 1|Draft
  // 2|Locked
  // 3|Pending
  // 4|Approved
  // 5|Rejected
  // 6|Completed
  // 7|Cancelled
  //pr status.when undraft ,check pending or locked???
  $node->field_pr_status[LANGUAGE_NONE][0]['value'] = 3;
  // $bis_info_all = get_bis_info_all($node->field_budget_items[LANGUAGE_NONE][0]['target_id']);
  // if($bis_info_all['f'] < 0) {
  //   $node->field_pr_status[LANGUAGE_NONE][0]['value'] = 2;
  //   //TODO auto flag
  //   watchdog('f', 'Lockedr', array(), WATCHDOG_NOTICE, 'link');
  // }
  if(isset($node->field_pr_author[LANGUAGE_NONE][0]['target_id']) && is_numeric($node->field_pr_author[LANGUAGE_NONE][0]['target_id'])) {
    $temp  = $node->field_pr_author[LANGUAGE_NONE][0]['target_id'];
    // $tempuid = $node->uid;
    $node->uid = $temp;
    // $node->field_pr_author[LANGUAGE_NONE][0]['target_id'] = $tempuid;
  }

   //add role after value begin

    $camplus_pr_range_settings = variable_get('camplus_pr_range_settings');
    // global $debug; 
    // dpm($total,'total');
    // if($debug) dpm($camplus_pr_range_settings,'$camplus_pr_range_settings');
    foreach ($camplus_pr_range_settings as $key => $value) {
      if($value['end']-$total >= 0) {
        $approve_rang = $key; //the $key+1 group settings.
        break;
      }
    }
    // $approve_status['approve_rang'] = $approve_rang;
    $workflow_settings = variable_get('camplus_pr_workflow_settings', '');
    //the first one is head,shift it!
    // dpm($workflow_settings,$approve_rang);
    $workflow_settings_node = $workflow_settings[$approve_rang];  
    $node->field_pr_role_involved[LANGUAGE_NONE][0]['value'] = serialize($workflow_settings_node);
    // dpm($workflow_settings_node,'$workflow_settings_node2');
    $workflow_settings_node = array_filter($workflow_settings_node);

    $workflow_settings_node = array_keys($workflow_settings_node);
    // dpm($workflow_settings_node,'$workflow_settings_node');
    if(isset($workflow_settings_node[1])){
      //0 5 header
      //1 6 manager
      //2 7 principal
      //3 8 borad
      $node->field_pr_rid_after[LANGUAGE_NONE][0]['value'] = $workflow_settings_node[1];//6
    }
    // dpm($node,'123');
  //add role after value  end

  node_save($node);
  drupal_goto('node/'.$node->nid);
}
function camplus_pr_status_update($vid, $status_id) {
  $status_update = db_update('field_data_field_pr_status')
  ->fields(array(
    'field_pr_status_value' => $status_id,
  ))
  // ->condition('entity_id', $nid)
  ->condition('revision_id', $vid)
  ->execute();

  $status_update1 = db_update('field_revision_field_pr_status')
  ->fields(array(
    'field_pr_status_value' => $status_id,
  ))
  // ->condition('entity_id', $nid)
  ->condition('revision_id', $vid)
  ->execute();
  return $status_update&&$status_update1;
}
/**
 * Implements hook_node_view().
 */
function camplus_pr_node_view($node, $view_mode, $langcode) {
  global $user;
  if(!$node->status &&$node->type ='purchase_request' && $user->uid == $node->uid){
    $node->content['undraft'] =  array(
      '#markup' => t('Submit'),
      '#prefix' => '<a class= "button" href="?q=node/'.$node->nid.'/undraft">',
      '#suffix' => '</a>', 
      '#weight' => -18,
    );
    $node->content['edit'] =  array(
      '#markup' => t('Edit'),
      '#prefix' => '<a class= "button" href="?q=node/'.$node->nid.'/edit">',
      '#suffix' => '</a>', 
      '#weight' => -19,
    );
  }

  if($node->type == 'budget_item' ) {
    //if not open mixable key, == not Enable Budget Pool, hide the field
    //@see node_view & purchase_request_node_form_validate()
    //只是隐藏而已，实际的动作是不可以通用，即submit 提交验证。
    if(!variable_get('camplus_pr_enable_mixable_key', 0)) {
      unset($node->content['field_mixable_key']);
    }  
  }
  //如果locked，除非unlockrole，其他人不允许看到该节点 lock=2
  
  if(arg(0)=='node' && $node->type == 'purchase_request' && $node->field_pr_status[LANGUAGE_NONE][0]['value'] == 2 && $node->uid != $user->uid) {
    // $flag = flag_load('pr_lock');
    // dvm(flag_flag_access($flag, $node->nid, 'flag',$user));
    // dpm($user->roles,variable_get('camplus_pr_unlock_role', '6'));
    if(!in_array(variable_get('camplus_pr_unlock_role', '6'), array_keys($user->roles))) {
      drupal_set_message(t('You cannot see loced PR!'), 'warning', FALSE);
      drupal_access_denied();
      module_invoke_all('exit');
      exit();
    }
  }
}
/**
 * Implements hook_permission().
 */
function camplus_pr_permission() {
	return array(
    'camplus purchase request approvable' =>  array(
      'title' => t('Approval for Purchase Request'),//审批资格 权限 View My Approve.Camplus Purchase Request approvable即审批资格 权限
      'restrict access' => TRUE,
    ),
    'camplus budget settings' =>  array(
      'title' => t('Camplus BI Settings'),//书记 权限 预算设置
      'restrict access' => TRUE,
    ),
    'camplus budget cross sectoral' =>  array(
      'title' => t('Non-Departmental Submission for Purchase Request'),//跨部门 add 预算 
      'restrict access' => TRUE,
    ),
    'view all purchase request' => array(
      'title' => t('View All Purchase Request'),
    ),
     'view loked purchase request' => array(
      'title' => t('View Loked Purchase Request'),
    ),
     'view my budget report' => array(
      'title' => t('View My Budget Report(group specific role)'),
    ),
    'view budget report' => array(
      'title' => t('View Budget Report'),
    ),
    // 'pr office submission' => array(//Enable Office Submission means Office Staff Mady help teachers to create, fill and submit the Purchase Request, but the Applicant will still be the teacher who request the purchase.
    //   'title' => t('Office Submission'),
    // ),
   );
}
/**
 * Implements hook_theme().
 */
function camplus_pr_theme() {
  return array(
    'camplus_pr_roles_weight_settings_form' => array(
      'render element' => 'form',
    ), 
    'camplus_pr_range_settings_form'  => array(
      'render element' => 'form',
    ),
    'camplus_pr_approve_settings_form'  => array(
      'render element' => 'form',
    ),  
    'camplus_pr_budget_settings_form' => array(
      'render element' => 'form',
    ),          
  );
}
/**
 * Implements hook_form_alter().
 */
function camplus_pr_form_alter(&$form, &$form_state, $form_id) {
  $forms = array('camplus_pr_range_settings_form','camplus_pr_roles_involved_settings_form');

	if(in_array($form_id, $forms)){
    drupal_add_css(drupal_get_path('module', 'camplus_pr').'/camplus_pr.css');
  }

  if($form_id == 'purchase_request_node_form') {
    // drupal_add_js(drupal_get_path('module', 'camplus_pr').'/camplus_pr.js');
    $form['bi_warning'] = array(
      '#markup' => 'Note:
<br/>1. The Amount Request should be lower than the Applicable Balance remained in the input form

<br/>2. After "Save" this Purchase Request Form, you need to "Submit" it for Approval Process

<br/>3. You can Edit or Delete after "Save" and before "Submit"

<br/>4. After "Submit", you CANNOT edit or delete, but you can "Cancel"

<br/>5. Cancelled applications will remain as records and cannot be edited or deleted',
      '#weight' => -100,
      '#prefix' => '<div id="bi_warning" class="messages warning">',
      '#suffix' => '</div>',
    );
    $form['#validate'][] = 'purchase_request_node_form_validate';
    $form['#submit'][] = 'purchase_request_node_form_submit_warning';
    $form['#attached']['js'][] = drupal_get_path('module', 'camplus_pr') . '/camplus_pr.js';

    //http://pm.intechnigence.com/node/110
    global $user;
    if(!in_array(variable_get('camplus_pr_help_role', '6'), array_keys($user->roles)) || !variable_get('camplus_pr_help_staff_enable', '0')) {
      $form['field_pr_author']['#access'] = FALSE;
    }
    $camplus_pr_range_settings = variable_get('camplus_pr_range_settings');
    $camplus_pr_file_settings = variable_get('camplus_pr_file_settings');
    $description = '';
    // dpm($camplus_pr_file_settings);
    // dpm($camplus_pr_range_settings);
    foreach ($camplus_pr_range_settings as $key => $value) {
      if(!$camplus_pr_file_settings["pr_quo_file_no_$key"]) {
        $str1 = t('no reference supplier required;');
      }else {
        $str1 = '<strong>'. $camplus_pr_file_settings["pr_quo_file_no_$key"].'</strong> '.t('reference supplier required;');
      }
      if(!$camplus_pr_file_settings["pr_quofile_require_$key"]) {
        $str2= '';
      }else {
        $str2 = t('Quotation file required;');
      }
      if(!$camplus_pr_file_settings["pr_ref_file_require_$key"]) {
        $str3= '';
      }else {
        $str3 = t('Reference Supplier Quotation file required');
      }
      $description .= 'HK$'.$value['begin'] .'-'. $value['end']  . ': ' .$str1. ' ' .$str2 . ' ' .$str3 .'<br/>';
    }
    $form['fgm_node_purchase_request_form_group_ref_supplier']['fields']['#description'] = $description;
    $form['field_pr_status']['#access'] = FALSE;
    $form['field_pr_staff']['#access'] = FALSE;
    $form['field_voucher_no']['#access'] = FALSE;
    $form['og_group_ref']['#access'] = FALSE;
    $form['field_pr_reference']['#access'] = FALSE;
    // dpm();
  }
  //if not open mixable key, == not Enable Budget Pool, hide the field
  //@see node_view & purchase_request_node_form_validate()
  //只是隐藏而已，实际的动作是不可以通用，即submit 提交验证。
  if($form_id == 'budget_item_node_form') {
    if(!variable_get('camplus_pr_enable_mixable_key', 0)) {
      unset($form['field_mixable_key']);
    }
  }
}
/**
 * Implements hook_node_submit().
 */
function camplus_pr_node_submit($node, $form, &$form_state) {


  if($node->type != 'purchase_request') return;
    //set PR Reference #

    $field_financial_year = camplus_pr_get_current_financial_year();
    $financial_year = substr($field_financial_year,0,4)-1;
    $financial_year_end = substr($field_financial_year,2,2);
    // $form_state['values']['field_pr_reference'][LANGUAGE_NONE][0]['value'] = variable_get('camplus_pr_no_pattern_prefix', 'PR').'-'.$financial_year .'/'. $financial_year_end ."-0000-".$node->nid;
    $node->field_pr_reference[LANGUAGE_NONE][0]['value'] = variable_get('camplus_pr_no_pattern_prefix', 'PR').'-'.$financial_year .'/'. $financial_year_end ."--".$node->nid;//0000
  // dpm($form_state,'form_state1');
  $fid = $form_state['input']['fgm_node_purchase_request_form_group_chosen']['fields']['items'][0]['field_pr_quotation_file'][LANGUAGE_NONE][0]['fid'];
  if($fid) {
    $file = file_load($fid);
    // dpm($fid,'field_pr_quotation_file');
    // field_attach_insert($entity_type, $entity)
    $field_file = (array) $file;
    $field_file['display'] = 1;
    $node->field_pr_quotation_file[LANGUAGE_NONE][] = $field_file;
  }
  // file_usage_add($file, 'file', $entity_type = 'node', $id = $node->nid);
  foreach ($form_state['input']['fgm_node_purchase_request_form_group_ref_supplier']['fields']['items'] as $key => $value) {
    # code...
    $fid = $value['field_pr_ref_quotation_file'][LANGUAGE_NONE][0]['fid'];
      if($fid) {
        $file = file_load($fid);

        $field_file = (array) $file;
        $field_file['display'] = 1;

        // dpm($file,'field_pr_ref_quotation_file');
        $node->field_pr_ref_quotation_file[LANGUAGE_NONE][] = $field_file;
        // file_usage_add($file, 'file', $entity_type = 'node', $id = $node->nid);
      }
  }
}

function purchase_request_node_form_validate($form, &$form_state) {
  // Budget Items field && Budget Items amount field validate
 
  $department = array();
  $total = 0;
  $howmany = 0;
  if($form_state['input']['fgm_node_purchase_request_form_group_budgets']['fields'])
  foreach ($form_state['input']['fgm_node_purchase_request_form_group_budgets']['fields'] as $key1 => $variable) {
    $field_budget_items_amount = 0;
    foreach ($variable as $key => $value) {
      if($value['field_budget_items']['und']=='_none' && $value['field_budget_items_amount']['und']['value']) {
        form_set_error('og_group_ref[und]['.$key1.'][default]', t('Please select which Budget Item you request'));
      }
      if(!$value['field_budget_items_amount']['und']['value'] && $value['field_budget_items']['und']!='_none') {
        form_set_error('og_group_ref[und]['.$key1.'][default]', t('Please fill the Budget Amount you request'));
      }
      
      if($value['field_budget_items_amount']['und']['value']<0) {
        form_set_error('og_group_ref[und]['.$key1.'][default]', t('The Budget Amount cannot be negative!'));
        //The Budget Amount you request cannot be --
      }
      $total += $value['field_budget_items_amount']['und']['value'];
      $field_budget_items_amount = $value['field_budget_items_amount']['und']['value'];
      $field_budget_items[$key] = $value['field_budget_items']['und'];
      if($field_budget_items[$key] == '_none') {
        form_set_error('[field_budget_items_amount][und][value]', t('Please select which Budget Item you request'));
        break;
      }

      // get department!
      if($node = node_load($field_budget_items[$key]))
      $department[] = $node->field_parents_department[LANGUAGE_NONE][0]['target_id'];
      //不能重复选择部门
      if(count(array_unique($field_budget_items)) != count($field_budget_items)) {
        form_set_error('[field_budget_items_amount][und][value]', t('Budget Items CANNOT repeat!'));
      }

      $field_budget_items_amounts[$key] = $value['field_budget_items_amount']['und']['value'];
      $bis_info_all = get_bis_info_all($field_budget_items[$key]);
      // dpm($bis_info_all);
  // form_set_error('[field_budget_items_amount][und][value]', t($field_budget_items_amounts[$key].'最大余额为负时'.$bis_info_all['f'].',不能预算！'));
      if($bis_info_all['f'] <= 0) {//最大余额 
        form_set_error('[field_budget_items_amount][und][value]', t('The balance in the Budget item you applied is already negative! Cannot Apply this Budget Item!'));//最大余额为负时,不能预算！
      }
      //超过最大余额，将要通用别人的
      if(($field_budget_items_amounts[$key] > $bis_info_all['f']) && !variable_get('camplus_pr_enable_mixable_key', 0) ) {//通用余额  get_bi_mixable_amount($field_budget_items[$key]
        form_set_error('[field_budget_items_amount][und][value]', t('You cannot apply amount larger than the Applicable Budget Balance!'));//您只能使用最大余额'.$bis_info_all['f'].' 不能通用 not Enable Budget Pool
      }  


      if($field_budget_items_amount > $bis_info_all['g']) {
        form_set_error('[field_budget_items_amount][und][value]', t('Your Requested Amount exceeds the Maximum Budget in your Department, your application CANNOT be submitted!'));
      }
      if($field_budget_items_amount > $bis_info_all['d']) {
        drupal_set_message(t('Your Requested Amount exceeds the Budgeted Amount, your application may not be approved!'), 'warning', FALSE);
      }
      if($field_budget_items_amounts[$key] > $bis_info_all['g']) {//通用余额  get_bi_mixable_amount($field_budget_items[$key]
        form_set_error('[field_budget_items_amount][und][value]', t('The Budget Item Amount you applied may be used by other Budget Item(s) in the same Budget Pool. So you cannot request this amount although it is smaller than the balance.'));//不能超过通用余额:'.$bis_info_all['g'].'如果数值小于提示数值，此时原因可能是别人通用你的l
      }

    }
     // form_set_error('[field_budget_items_amount][und][value]', t('test!!!'));
  }
  if(count($form_state['input']['fgm_node_purchase_request_form_group_budgets']['fields']['items'])>1 && empty($form_state['values']['field_multiple_bi_reason'][LANGUAGE_NONE][0]['value'])) {
    form_set_error('field_multiple_bi_reason', t('You MUST specify reason of using more than 1 Budget Item?'));
  }
  //您不能跨部门预算
  if(count(array_unique($department))!=1) {
     form_set_error('[field_budget_items_amount][und][value]', t('You CANNOT request a purchase from different Budget Item!'));
  }
  // Budget Items field && Budget Items amount field validate end
 
  // devel 显示用户输入值
  // dpm($field_budget_items,'$field_budget_items');
  // dpm($field_budget_items_amounts,'$field_budget_items_amounts');
    if($form_state['input']['field_payment_from_students'][LANGUAGE_NONE][0]['value'] < 0) {
      form_set_error('field_payment_from_students[und][0][value]', t('The amount paid from students cannot be negative!'));
    }
    $chosen_price = $total + $form_state['input']['field_payment_from_students'][LANGUAGE_NONE][0]['value'];

    $form_state['values']['fgm_node_purchase_request_form_group_chosen']['fields']['items'][0]['field_chosen_price'][LANGUAGE_NONE]['value'] = $chosen_price;
    // $form_state['input']['field_chosen_price'][LANGUAGE_NONE][0]['value'] = $chosen_price;

    $camplus_pr_range_settings = variable_get('camplus_pr_range_settings'); 
    // watchdog('camplus_pr-field_chosen_price', $chosen_price, array(), WATCHDOG_NOTICE, 'link');
    $approve_rang = 0;
    foreach ($camplus_pr_range_settings as $key => $value) {
      if($value['end']-$chosen_price >= 0) {
        $approve_rang = $key;
        break;
      }
    }
    $camplus_pr_file_settings = variable_get('camplus_pr_file_settings');

    $pr_quofile_require = $camplus_pr_file_settings["pr_quofile_require_$approve_rang"];

    $pr_quo_file_no = $camplus_pr_file_settings["pr_quo_file_no_$approve_rang"];
    $pr_ref_file_require = $camplus_pr_file_settings["pr_ref_file_require_$approve_rang"];
    // $file_settings = variable_get('camplus_pr_file_settings');
    // dpm($file_settings);
    if($pr_quofile_require && !$form_state['input']['fgm_node_purchase_request_form_group_chosen']['fields']['items'][0]['field_pr_quotation_file'][LANGUAGE_NONE][0]['fid']) {
      form_set_error('files[field_pr_quotation_file_und_0]', t('You MUST upload the quotation file from the Chosen Supplier!'));
    }
    
    //['field_pr_quotation_file'][LANGUAGE_NONE][0]['fid']
    // $chosen_price = $total + $form_state['input']['field_payment_from_students'][LANGUAGE_NONE][0]['value'];
    if(!strlen($form_state['input']['field_lower_price_remark'][LANGUAGE_NONE][0]['value']) && $camplus_pr_file_settings["pr_quo_file_no_$approve_rang"] > 0 && $form_state['values']['field_pr_sole_supplier'][LANGUAGE_NONE][0]['value'] != 1)
    foreach ($form_state['input']['fgm_node_purchase_request_form_group_ref_supplier']['fields']['items'] as $key => $referenced) {
      if($chosen_price > $referenced['field_referenced_price'][LANGUAGE_NONE]['value']) {
        form_set_error('fgm_node_purchase_request_form_group_chosen[fields][items][0][field_chosen_price][und][value]', t('Your quoted reference price is smaller than the price from chosen supplier, you must specify reason.
'));//$field_name.
      }
    }

    if($pr_ref_file_require && $form_state['values']['field_pr_sole_supplier'][LANGUAGE_NONE][0]['value'] != 1) {
      foreach ($form_state['input']['fgm_node_purchase_request_form_group_ref_supplier']['fields']['items'] as $key => $fields) {
        foreach ($fields as $field_name => $value) {
          if($field_name == 'field_pr_ref_quotation_file') {
            if(!$value[LANGUAGE_NONE][0]['fid']) {
               form_set_error('files[field_pr_quotation_file_und_0]', t('Reference Supplier Quotation file required!'));
            };
          }
        }
      }
    }

    if($pr_quo_file_no != 0 && $form_state['values']['field_pr_sole_supplier'][LANGUAGE_NONE][0]['value'] != 1) 
    foreach ($form_state['input']['fgm_node_purchase_request_form_group_ref_supplier']['fields']['items'] as $key => $fields) {
      foreach ($fields as $field_name => $value) {
        if($field_name != 'field_pr_ref_quotation_file') {
          if(empty($value[LANGUAGE_NONE]['value'])){
            // dpm( $field_name.t('must have value'));
             form_set_error('', t('You need to provide reference supplier(s) information as well'));//$field_name.
          };
        }else {

        }
      }
    }
    if($pr_quo_file_no != 0 && $form_state['values']['field_pr_sole_supplier'][LANGUAGE_NONE][0]['value'] != 1 && $pr_quo_file_no > count($form_state['input']['fgm_node_purchase_request_form_group_ref_supplier']['fields']['items']) ) {
      form_set_error('field_budget_items_amount', t('You MUST upload  '.$pr_quo_file_no .' quotation file(s) from the Reference Supplier!'));
    }


    // set field_pr_staff  == current user;
    global $user;
    $form_state['input']['field_pr_staff'][LANGUAGE_NONE] = $user->uid;
    $form_state['values']['field_pr_staff'][LANGUAGE_NONE][0]['target_id'] = $user->uid;
    //set field_pr_author == node->uid
    if(isset($form_state['input']['field_pr_author']) && is_numeric($form_state['input']['field_pr_author'][LANGUAGE_NONE])){
      $form_state['values']['uid'][LANGUAGE_NONE] = $form_state['input']['field_pr_author'][LANGUAGE_NONE];
    }


    //http://pm.intechnigence.com/node/138
    $camplus_pr_range_settings = variable_get('camplus_pr_range_settings');
    $end = end($camplus_pr_range_settings);
    if($chosen_price > $end['end']) form_set_error('field_budget_items_amount', t('Purchase Amount larger than '.$end['end'].' requiring Tender Process! The system will not handle it!'));

    if(form_get_errors()) {
      return;
    }
 //    drupal_set_message(t('This Application has not yet been submitted for Apporval Process.
 // <br>Reminded that, due to submission(s) by others, the Applicable Balance may change when you "Submit".'), 'warning', FALSE);

}

function purchase_request_node_form_submit_warning($form, &$form_state) {

  drupal_set_message(t('This Application has not yet been submitted for Apporval Process. <br>Reminded that, due to submission(s) by others, the Applicable Balance may change when you "Submit".'), 'warning', FALSE);
}
function camplus_pr_field_widget_form_alter(&$element, &$form_state, $context) {
  //field_budget_items
  //必须是当前年份的预算项目
  //普通角色只能选择本部门的
  //Groups audience == 普通角色所属部门
  if(isset($element['#field_name']) && $element['#field_name'] == 'field_budget_items') {
    // $element['#ajax'] = array(
    //   'callback' => 'ajax_get_bi_mixable_amount_callback',
    //   'wrapper' => 'bi_warning',
    //   'method' => 'replace',
    //   'effect' => 'fade',
    // );
    if (!isset($element['#process'])) {
      $element['#process'] = array();
    }
    array_unshift($element['#process'], 'form_process_field_budget_items');
  }
}
function form_process_field_budget_items(&$element) {
    if(strpos($element['#id'], 'field-budget-items-und')  !== FALSE ) {
        //如果角色不是管理角色，只显示所属部门的子预算项目
        global $user;
        $rid = variable_get('camplus_pr_help_role', '6');

        if(!user_access('camplus budget cross sectoral') ||  in_array($rid, array_keys($user->roles))) { //
          // Load in the current user's group entity ID's
          $department = array();
          if(!in_array($rid, array_keys($user->roles))) {
            $groups = og_get_entity_groups();
            // Load the entities object ID's
            $nodes = node_load_multiple($groups['node']);
            foreach ($nodes as $key => $node) {
              if($node->type == 'school_department'){
                $department[] = $key;
                // break;
              }else{
                continue;
              }
            }
          }
     

        $budget_items = $element['#options'];

        if(isset($budget_items) && is_array($budget_items))
        foreach ($budget_items as $budget_item_nid => $title) {
          
          $node = node_load($budget_item_nid);

          if(!$node) continue;
          // //expect locked prs
          // if($pr_node->field_pr_status[LANGUAGE_NONE][0]['value'] == 2) {
          //   continue;
          // }
          $element['#options'][$budget_item_nid] = $node->title .' - '. $node->body[LANGUAGE_NONE][0]['safe_value'];
          //去除不是当前学年的
          if(!isset($node->field_financial_year[LANGUAGE_NONE][0]['value']) || $node->field_financial_year[LANGUAGE_NONE][0]['value'] != camplus_pr_get_current_financial_year() ){
            //|| !in_array($node->field_parents_department[LANGUAGE_NONE][0]['target_id'], $department)
            unset($element['#options'][$budget_item_nid]);
          }

          $bis_info = get_bis_info_all($budget_item_nid);
          if($bis_info['f'] <= 0) {
            unset($element['#options'][$budget_item_nid]); 
          }
          $rid = variable_get('camplus_pr_help_role', '6');

          if(in_array($rid, array_keys($user->roles))) {
            continue;
          }elseif(!in_array($node->field_parents_department[LANGUAGE_NONE][0]['target_id'], $department)){
            unset($element['#options'][$budget_item_nid]);
          }
          // if($bis_info['g'] == 0) {
          //   dpm('通用余额为0,不可再做预算！');
          //   unset($element['#options'][$budget_item_nid]); 
          // }

          $element['#options']['_none'] = t('- Select a value -');
          $element['#default_value'] = '_none';

        }
      }
      else {
        $budget_items = $element['#options'];
        if(isset($budget_items) && is_array($budget_items))
        foreach ($budget_items as $budget_item_nid => $title) {
          $node = node_load($budget_item_nid);
          if(!$node) continue;
          $element['#options'][$budget_item_nid] = $node->title .' - '. $node->body[LANGUAGE_NONE][0]['safe_value'];
            //去除不是当前学年的
            if(!isset($node->field_financial_year[LANGUAGE_NONE][0]['value']) || $node->field_financial_year[LANGUAGE_NONE][0]['value'] != camplus_pr_get_current_financial_year() ) {
              //|| !in_array($node->field_parents_department[LANGUAGE_NONE][0]['target_id'], $department)
              unset($element['#options'][$budget_item_nid]);
            }
          
        }
      }
    }
  return  $element;
}
/**
 * Implements hook_admin_path().
 */
function camplus_pr_admin_paths_alter(&$paths) {
  $paths['node/add/purchase-request'] = FALSE;
  $paths['node/add/budget-item'] = FALSE;  
  $paths['node/add/school-department'] = FALSE;
  $paths['node/%node/edit'] = FALSE;
}
/**
 * Callback element needs only select the portion of the form to be updated.
 * Since #ajax['callback'] return can be HTML or a renderable array (or an
 * array of commands), we can just return a piece of the form.
 */
// function ajax_get_bi_mixable_amount_callback_delete($form, &$form_state) {
//   // $form_state['rebuild'] = TRUE;
//   dpm($form_state['input'],'why not the choose value of BI?');

//   $field_budget_items = $form_state['values']['field_budget_items'][LANGUAGE_NONE];
//   $field_budget_items_amount = $form_state['values']['field_budget_items_amount'];
//   foreach ($field_budget_items as $key => $budget_nid) {
//     $bis_info_all = get_bis_info_all($budget_nid['target_id']);
//     // $mixable_amount = get_bi_mixable_amount($budget_nid['target_id']);
//     $output .= $budget_nid['target_id'].'-->'.$bis_info_all['g'].'-->'.$bis_info_all['f'].'<br/>';
//   }
//   //user input value > max mix value

//   // dpm($form_state['values']['field_budget_items'],'why not the choose value of BI?');

//   {// todo 获取预算项目的max值
//    $commands[] = ajax_command_replace('#bi_warning', $html='<div id="bi_warning" class="messages warning">budget_nid-->This BI余额--->可通用余额<br/>'.$output.'</div>', $settings = NULL);
//    //您不能跨部门选择
//    // 该部门的为负值，不可选择
//   }
//   return array('#type' => 'ajax', '#commands' => $commands);
// }

/**
 * Implements hook_init().
 */
function camplus_pr_init() {
  $GLOBALS['debug'] = TRUE;
  $public_groups = druedu_user_get_nodes_by_group('school_department');
  $variables = array();
  foreach ($public_groups as $g_nid => $g_node) {
    $all_subjects_node = camplus_pr_get_bis_by_year($g_nid,$financial_year = NULL);
    foreach ($all_subjects_node as $s_nid => $s_node) {
      $bis_info_all = get_bis_info_all($s_nid);
      $variables[$s_nid] = $bis_info_all['d']; 
    }
  }
  $variables['_none'] = 0; 
  drupal_add_js(array('camplus_pr' => $variables), 'setting');
}

function camplus_pr_get_current_financial_year(){
  $financial_year_begin = variable_get('camplus_pr_financial_year_begin', '09-01');
  $financial_year_end = variable_get('camplus_pr_financial_year_end', '08-31');
  //2014-08-31 00:00:00
  $financial_year_end = strtotime(date('Y').'-'.$financial_year_end.' 23:59:59');
  if(time()<=$financial_year_end) {
    $financial_year =  date('Y').'-01-01 00:00:00';//2013学年度
  }else{
    $financial_year =  (date('Y')+1).'-01-01 00:00:00';//2013+1学年度
  }
  return  $financial_year;
}
//seems no user.
function camplus_pr_approve_flag_generate($key) {
  $flags = array();
  // Exported flag: "Bookmarks".
  $flags[$key] = array (
    'content_type' => 'node',
    'title' => 'Approve',
    'global' => '0',
    'types' => 
      array (
        0 => 'purchase_request',
      ),
    'flag_short' => 'Approve this PR',
    'flag_long' => 'Approve this Purchase Request',
    'flag_message' => 'This Purchase Request has been Approved',
    'unflag_short' => 'Unbookmark this',
    'unflag_long' => 'Remove this post from your bookmarks',
    'unflag_message' => 'This post has been removed from your bookmarks',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
      array (
        'flag' => 
        array (
          0 => 2,
        ),
        'unflag' => 
        array (
          0 => 2,
        ),
      ),
    'weight' => 0,
    'show_on_form' => 1,
    'access_author' => '',
    'show_on_page' => 1,
    'show_on_teaser' => 1,
    'show_contextual_link' => false,
    'i18n' => 0,
    'api_version' => 2,
  );
  return $flags;
}

//获取该年度的所有预算budget_item
//camplus_pr_get_bis_by_year
//financial_year 2013-01-01 00:00:00

function camplus_pr_get_bis_by_year($department_nid, $financial_year = NULL) {
  if(!$financial_year){
    $financial_year_begin = variable_get('camplus_pr_financial_year_begin', '09-01');
    $financial_year_end = variable_get('camplus_pr_financial_year_end', '08-31');
    //2014-08-31 00:00:00
    $financial_year_end = strtotime(date('Y').'-'.$financial_year_end.' 23:59:59');
    if(time()<=$financial_year_end) {
      $financial_year =  date('Y').'-01-01 00:00:00';//2013学年度
    }else{
      $financial_year =  (date('Y')+1).'-01-01 00:00:00';//2013+1学年度
    }
  }

  $query = db_select('field_data_field_financial_year', 'f');
  $query->join('node','n','n.nid = f.entity_id');

      // $query = db_select('og_membership', 'og');
    $query->join('og_membership','og','n.nid = og.etid');

  $nids = $query
    ->fields('f', array('entity_id'))//nid
    ->condition('n.type ','budget_item')
    ->condition('f.field_financial_year_value',$financial_year)
    
    ->condition('og.gid ',$department_nid)//$gid

    ->condition('n.status',1)
    ->orderBy('n.created ', 'ASC')
    ->execute();
  $nodes = node_load_multiple($nids->fetchCol());
  return $nodes ? $nodes : array();
}

//获取该预算下的所有PR
//get_group_nodes_by_uid/field_financial_year
function camplus_pr_get_prs($budget_nid, $uid = NULL) {
  //strtotime($field_financial_year);
  $query = db_select('field_data_field_budget_items', 'f');
  $query->join('node','n','n.nid = f.entity_id');
  $query = $query
    ->fields('f', array('entity_id'))//nid
    ->condition('f.field_budget_items_target_id',$budget_nid);
  if($uid && is_numeric($uid)) {
     $query = $query->condition('n.status',1);
  }
    
  $query = $query->condition('n.status',1)
    ->orderBy('n.created ', 'ASC')
    ->execute();
  $nodes = node_load_multiple($query->fetchCol());
  return $nodes ? $nodes : array();
}

/**
 * Implements hook_menu_alter().
 */
function camplus_pr_menu_alter(&$items) {
  $items['node/%node/edit']['access callback'] = 'node_access4camplus_pr';
}
/**
 * @see node_access
 */
function node_access4camplus_pr($op, $node, $account = NULL) {
  if($node->type == 'purchase_request') {
    //一旦发布 not be a Draft，不可编辑
    global $user; 
     // && !in_array('administrator', $user->roles) 
    if($node->status && $user->uid <> 1) {
      // dpm('一旦发布 not be a Draft，不可编辑',__LINE__);
      return false;
    }
    return node_access($op, $node, $account);
  }else {
    return node_access($op, $node, $account);
  }
 }

 /**
 * Cancel 后，不可unflag/unCancel
 * @see flag_flag:access()
 */
function camplus_pr_flag_access($flag, $content_id, $action, $account) {
  global $debug;
  if($flag->name == 'cancel' || $flag->name == 'paid') {
    $node = node_load($content_id);
    // if($node->uid != $account->uid) return;
    if(!$node || !$node->status) return;
    $widget = _camplus_pr_get_approve_rate($node);
    if(!isset($widget->id)) return;
    $approve_status = _rate_pr_check_permissions($node,$widget);
    if($debug) dpm($approve_status);
    //已经标记Cancel，不可再标记Paid
    if($flag->name == 'paid' && isset($approve_status['flags']['cancel']) && $approve_status['flags']['cancel'] ){
      if($debug) dpm('已经标记Cancel，不可再标记Paid',__LINE__);
      return FALSE;
    }
    //6 == completed paid.
    //1 == draft. when draft .can not flag paid.
    if($flag->name == 'cancel') {
     if($node->field_pr_status[LANGUAGE_NONE][0]['value'] == 6 || $node->field_pr_status[LANGUAGE_NONE][0]['value'] == 1 ){// && isset($approve_status['flags']['paid']) && $approve_status['flags']['paid'] 
            if($debug) dpm('已经标记Paid，不可再标记Cancel',__LINE__);
            return FALSE;
       }
    }
     
    //还未全部审核/REJECT，manager不可标记paid
    if($flag->name == 'paid' &&($approve_status['workflow_status'] == 'pending' ||$approve_status['workflow_status'] == 'reject')){
      if($debug) dpm('还未全部审核，manager不可标记paid!',__LINE__);
      return FALSE;
    }
    //是否可以Cancel与审核状态无关。
    
    //未发布状态，manager/author不能看到flag：Paid & flag：cancel
    if(!$node->status) {
      return FALSE;
    }
  }
}

/**
 * @param nid or node
 * get every row of the table.
 * 获取预算基本信息
 */
function get_bis_info($node) {
  global $debug;
  if(is_numeric($node)) {
    $budget_nid = $node;
    $bi_node = node_load($budget_nid);
  }else{
    $budget_nid = $node->nid;
    $bi_node = $node;
  }
    
  $bis = array();
  if(!$bi_node->nid) return $bis; // not exist the BI node.
  if (!isset($bi_node->field_pr_budget[LANGUAGE_NONE][0]['value'])) {
    $bis['amount'] = 0;
  }else {
    $bis['amount'] = $bi_node->field_pr_budget[LANGUAGE_NONE][0]['value'];
  }
  //已批支
  //已批支出 get all PRs begin
        $prs = camplus_pr_get_prs($budget_nid);
         $pending = 0;
         $approved = 0;
         $rejectd = 0;
         // get  approved appending and rejectd
         foreach ($prs as $nid => $pr_node) {
            // 排除canceled PRs
            $flags = flag_get_counts('node', $nid, $reset = FALSE);
            if(isset($flags['cancel']) && $flags['cancel']){
               if($debug) dpm('canceled pr:'.$nid,__LINE__);
               continue;
            }
           $widgets = rate_get_active_widgets('node', $pr_node->type);
           //get pr item
           foreach ($pr_node->field_budget_items[LANGUAGE_NONE] as $key => $value) {
            if($value['target_id'] ==  $budget_nid) {
              //field_budget_items_amount_index
              $bi_index = $key;
              break;
            }
           }
            foreach ($widgets as $widget_id => $widget) {
              if($widget->name == 'approve'){
                $widget->id = $widget_id;
                $approve_status = _rate_pr_check_permissions($pr_node,$widget);
                switch ($approve_status['workflow_status']) {
                  case 'pending':
                    $pending += $pr_node->field_budget_items_amount[LANGUAGE_NONE][$bi_index]['value'];
                    break;
                  case 'approved':
                    $approved += $pr_node->field_budget_items_amount[LANGUAGE_NONE][$bi_index]['value'];
                    break;
                  default: //rejectd FALSE
                    $rejectd += $pr_node->field_budget_items_amount[LANGUAGE_NONE][$bi_index]['value'];
                    break;
                }
                break;
              }else{
                continue;
              }
            }
         }
  //已批支出 get all PRs end
  $bis['approved'] = $approved;
  $bis['pending'] = $pending ;
  $bis['rejectd'] = $rejectd ;
  if(!isset($bi_node->field_pr_allowance[LANGUAGE_NONE][0]['value'])) {
     $bis['allowance'] = 0;
  }else {
    $bis['allowance'] = $bi_node->field_pr_allowance[LANGUAGE_NONE][0]['value'];
  }
  if(!isset($bi_node->field_mixable_key[LANGUAGE_NONE][0]['value'])) {
    $bis['mixable_key'] = 0;
  }else {
   $bis['mixable_key'] = $bi_node->field_mixable_key[LANGUAGE_NONE][0]['value'];
  }
  return $bis;
}
/**
 * 获取通用余额
 */
function get_bi_mixable_amount($budget_nid) {
  $bi_node = node_load($budget_nid); 
  $bi_item = get_bis_info($bi_node);


  if(!isset($bi_node->field_mixable_key[LANGUAGE_NONE][0]['value'])) return $bi_item['amount']-$bi_item['approved']-$bi_item['pending']+$bi_item['allowance'];
  $mixable_amount = 0;
  $mixable_key = $bi_node->field_mixable_key[LANGUAGE_NONE][0]['value'];
  $department_nid = $bi_node->field_parents_department[LANGUAGE_NONE][0]['target_id'];
  $financial_year = $bi_node->field_financial_year[LANGUAGE_NONE][0]['value'];
  $bis = camplus_pr_get_bis_by_year($department_nid,$financial_year);
  // get  approved appending and rejectd

  foreach ($bis as $nid => $node) {
    if(isset($node->field_mixable_key[LANGUAGE_NONE][0]['value']) && $node->field_mixable_key[LANGUAGE_NONE][0]['value'] == $mixable_key){
      $bi_item = get_bis_info($node);
      $max_overage = $bi_item['amount']-$bi_item['approved']-$bi_item['pending']+$bi_item['allowance'];
      $mixable_amount += $max_overage;
    }
  }
  $return['mixable_amount'] = $mixable_amount;
  return $mixable_amount;
}
/**
 * 获取预算所有信息
 * @see logic.png
 */
function get_bis_info_all($budget_nid) {
  global $debug;
  $node = node_load($budget_nid);
  $row = array();
  if(isset($node->field_pr_budget[LANGUAGE_NONE])) {
    $field_pr_budget = $node->field_pr_budget[LANGUAGE_NONE][0]['value'];
    $row['a'] = $field_pr_budget;
  }else{ 
    $field_pr_budget = 0;
    $row['a'] = '-';
  }
  //已批支出 get all PRs
  $prs = camplus_pr_get_prs($budget_nid);
  $pending = 0;
  $approved = 0;
  $rejectd = 0;
  // get  approved appending and rejectd
   foreach ($prs as $nid => $pr_node) {
      // 排除canceled PRs
      $flags = flag_get_counts('node', $nid, $reset = FALSE);
      if(isset($flags['cancel']) && $flags['cancel']){
         if($debug) dpm('canceled pr:'.$nid,__LINE__);
         continue;
      }
      //expect locked prs
      // if($pr_node->field_pr_status[LANGUAGE_NONE][0]['value'] == 2) {
      //   continue;
      // }
     $widgets = rate_get_active_widgets('node', $pr_node->type);
     //get pr item
     foreach ($pr_node->field_budget_items[LANGUAGE_NONE] as $key => $value) {
      if($value['target_id'] ==  $budget_nid) {
        //field_budget_items_amount_index
        $bi_index = $key;
        break;
      }
     }
      foreach ($widgets as $widget_id => $widget) {
        if($widget->name == 'approve'){
          $widget->id = $widget_id;
          $approve_status = _rate_pr_check_permissions($pr_node,$widget);
          switch ($approve_status['workflow_status']) {
            case 'pending':
              $pending += $pr_node->field_budget_items_amount[LANGUAGE_NONE][$bi_index]['value'];
              break;
            case 'approved':
              $approved += $pr_node->field_budget_items_amount[LANGUAGE_NONE][$bi_index]['value'];
              break;
            default: //rejectd FALSE
              $rejectd += $pr_node->field_budget_items_amount[LANGUAGE_NONE][$bi_index]['value'];
              break;
          }
          break;
        }else{
          continue;
        }
      }
   }
  $row['b'] = sprintf("%01.2f", $approved);

  $row['c'] = sprintf("%01.2f", $pending);
  $row_d = $field_pr_budget - $approved - $pending;
  $row['d'] = sprintf("%01.2f", $field_pr_budget - $approved - $pending);// '预算余额';
  if(isset($node->field_pr_allowance[LANGUAGE_NONE])) {
    $row_e = $node->field_pr_allowance[LANGUAGE_NONE][0]['value'];
    $row['e'] = $row_e;
  }else{
    $row_e = 0;
    $row['e'] = 0;
  }
  $row['f'] = sprintf("%01.2f", $row_d + $row_e);//max余额
  if(isset($node->field_mixable_key[LANGUAGE_NONE])) {
    $row['mixable_key'] = $node->field_mixable_key[LANGUAGE_NONE][0]['value'];
  }else{
    $row['mixable_key'] = NULL;
  }
  $row['g'] = get_bi_mixable_amount($budget_nid);//'通用余额';
  return $row;
}


function camplus_pr_views_pre_render(&$view) {
  global $user;
  $camplus_pr_approvable_role_involved = variable_get('camplus_pr_approvable_role_involved','');
  if(!($view->name == 'purchase_request_list' && $view->current_display == 'pr_approval')) return;

  $unset = FALSE;
  foreach ($camplus_pr_approvable_role_involved as $key => $value) {
    //是否有审核权限
    if($value && in_array($key, $user->roles)) {
      $unset = TRUE;
    }
  }
  //如果我不在审核队列，全部unset
  if(!$unset){
    // dpm('如果我不在审核队列，全部unset');
    $view->result = array();
  }
  foreach ($view->result as $key => $value) {
  //所有等待我处理的PRs
    $node = node_load($value->nid);   //pr node
    // if($node->status == 0) {echo  'Draft'; return;}
    $show_flag = TRUE;
    $flags = flag_get_counts('node', $node->nid, $reset = FALSE);
    if(isset($flags['paid']) && $flags['paid']) {
      $show_flag = FALSE;
    }

    $widgets = rate_get_active_widgets('node', $node->type);
    foreach ($widgets as $widget_id => $widget) {
      //没有权限时，清楚rate
      $widget->id = $widget_id;
      if($widget->name == 'approve') {
        $approve_status = _rate_pr_check_permissions($node,$widget);
        // dpm ($approve_status['workflow_status']);
        //等待penging
        if($approve_status['workflow_status'] != 'pending' && !camplus_pr_get_vote($node)) unset($view->result[$key]);
        //等待我 TODO
        //todo: 
        // unset rate widget 如果我的上一级部门没有审核的话，在views里不显示。可以用veiws template实现，
        //如果$approve_status['permit_flag'] = FALSE; 则不显示
        if(!$approve_status['permit_flag'] || !$show_flag) {
            // 根据PR节点的总额确定which审批流程
            // 在上一个审批流程没有确定前 其他后续
           unset($view->result[$key]);
          }
        }                
        break;
      }
    }
  // dpm($view);
  //   dpm($user->roles);
  //   dpm($camplus_pr_approvable_role_involved);
}


